package view.admin;

import model.Live;
import funcation.select.SelectAdminInfo;
import funcation.select.SelectStudentsInfo;
import funcation.selectview.SelectCurrentAdminView;
import funcation.update.UpdateLive;
import util.JFrameUtilKt;
import util.SetColorKt;
import util.StackFrame;
import util.UserService;
import view.menu.AdminMenu;

import javax.swing.*;
import java.awt.event.*;
import java.util.Vector;

/**
 *
 * @author Joki
 */
public class AdminBaseManageFrame extends StackFrame {

    /**
     * Creates new form AdminBaseManageFrame
     */
    public AdminBaseManageFrame() {
        super("");
        initComponents();
        JFrameUtilKt.init(this,580,430);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        livePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        liveTable = new javax.swing.JTable();
        dormTextField = new javax.swing.JTextField();
        bedNoTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        snoTextField = new javax.swing.JTextField();
        bt_insert = new javax.swing.JButton();
        bt_select = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        SetColorKt.setWhite(bt_back,bt_delete,bt_insert,bt_select);



        jTabbedPane1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        liveTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null,null},
                        {null, null, null, null,null},
                        {null, null, null, null,null},
                        {null, null, null, null,null}
                },
                new String [] {
                        "宿舍", "床位号", "学号", "姓名","联系方式"
                }
        ));


        LiveTableKt.fillTable(liveTable,new SelectCurrentAdminView().selectAllLiveByApartNo(
                new SelectAdminInfo().select(UserService.getInstance().getCurrentUser().getNo())));

        jScrollPane3.setViewportView(liveTable);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel1.setText("宿舍号");

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel2.setText("床位号");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel3.setText("学号");

        bt_insert.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        bt_insert.setText("添加");
        bt_insert.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                String sno = snoTextField.getText();
                System.out.println(new SelectStudentsInfo().select(sno).toString());

                Live live = new Live(new SelectAdminInfo()
                        .select(UserService.getInstance().getCurrentUser().getNo()).getApartNo(),
                        dormTextField.getText(),Integer.parseInt(bedNoTextField.getText()),
                        sno,new SelectStudentsInfo().select(sno).getName(),
                        new SelectStudentsInfo().select(sno).getTel());
                int result = new UpdateLive().updateLive(live);
                if (result < 0){
                    JOptionPane.showMessageDialog(AdminBaseManageFrame.this,
                            "添加失败！可能是不存在此学生","提示",JOptionPane.WARNING_MESSAGE);
                }else {
                    JOptionPane.showMessageDialog(AdminBaseManageFrame.this,"添加成功");
                }
            }
        });

        bt_select.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        bt_select.setText("查询");
        bt_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_selectActionPerformed(evt);
            }
        });

        bt_delete.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        bt_delete.setText("删除");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        bt_back.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        bt_back.setText("返回");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout livePanelLayout = new javax.swing.GroupLayout(livePanel);
        livePanel.setLayout(livePanelLayout);
        livePanelLayout.setHorizontalGroup(
                livePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                        .addGroup(livePanelLayout.createSequentialGroup()
                                .addGroup(livePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(livePanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bedNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(snoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(livePanelLayout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(bt_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bt_select, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(livePanelLayout.createSequentialGroup()
                                                .addGap(151, 151, 151)
                                                .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        livePanelLayout.setVerticalGroup(
                livePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(livePanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(livePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dormTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bedNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(snoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(livePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bt_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bt_select, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("宿舍管理", livePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void bt_selectActionPerformed(java.awt.event.ActionEvent evt) {
        String dormNo = dormTextField.getText();
        String sno = snoTextField.getText();
        /**
         * 如果宿舍号和床号都为空，table中的内容填充为当前用户管理的公寓住宿信息
         */
        if (dormNo.isEmpty() && bedNoTextField.getText().isEmpty() && sno.isEmpty()){
            LiveTableKt.fillTable(liveTable,new SelectCurrentAdminView().selectAllLiveByApartNo(
                    new SelectAdminInfo().select(UserService.getInstance().getCurrentUser().getNo())
            ));
        }else if (!dormNo.isEmpty() && bedNoTextField.getText().isEmpty()){
            LiveTableKt.fillTable(liveTable,new SelectCurrentAdminView().selectAllLiveByDormNo(
                    new SelectAdminInfo().select(UserService.getInstance().getCurrentUser().getNo()),dormNo
            ));
        }else if (!dormNo.isEmpty() && !bedNoTextField.getText().isEmpty()){
            int bedNo = Integer.parseInt(bedNoTextField.getText());
            Vector<Live> lives = new Vector<>();
            lives.add(new SelectCurrentAdminView().selectConcreteLive(new SelectAdminInfo().select(
                    UserService.getInstance().getCurrentUser().getNo()),dormNo,bedNo));

            LiveTableKt.fillTable(liveTable,lives);
        }else if (dormNo.isEmpty() && bedNoTextField.getText().isEmpty() && !sno.isEmpty()){
            Vector<Live> lives = new Vector<>();
            lives.add(new SelectCurrentAdminView().selectBySno(new SelectAdminInfo().select(
                    UserService.getInstance().getCurrentUser().getNo()),sno));

            LiveTableKt.fillTable(liveTable,lives);
        }
    }

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {
        int result = new UpdateLive().clearSno(LiveTableKt.getLiveInfo(liveTable));
        if (result < 0){
            JOptionPane.showMessageDialog(AdminBaseManageFrame.this,
                    "删除失败！","提示",JOptionPane.WARNING_MESSAGE);
        }else {
            JOptionPane.showMessageDialog(AdminBaseManageFrame.this,"删除成功！");
        }
    }

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }


    // Variables declaration - do not modify
    private javax.swing.JTextField bedNoTextField;
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_insert;
    private javax.swing.JButton bt_select;
    private javax.swing.JTextField dormTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel livePanel;
    private javax.swing.JTable liveTable;
    private javax.swing.JTextField snoTextField;
    // End of variables declaration
}
