package view.supervisor;

/**
 * Created by Lenovo on 2017/6/13.
 */

import funcation.update.UpdateApartment;
import model.Apartment;
import funcation.select.SelectApartments;
import util.SetColorKt;
import util.StackFrame;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Lenovo
 */
public class EditApartmentJFrame extends StackFrame {
    private Apartment apartment=null;
    private Apartment agoApartment =null;
    /**
     * Creates new form EditApartmentJFrame
     */
    public EditApartmentJFrame(Apartment apartment1) {
        super("");
        agoApartment =apartment1;
        //apartment=apartment1;
        initComponents();
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        NoLabe = new JLabel();
        NameLabe = new JLabel();
        LocationLabe = new JLabel();
        FloorLabe = new JLabel();
        MaxLabe = new JLabel();
        InLabe = new JLabel();
        NoTextField = new JTextField();
        NameTextField = new JTextField();
        LocationTextField = new JTextField();
        FloorTextField = new JTextField();
        MaxTextField = new JTextField();
        InTextField = new JTextField();
        ManagerNoLabe = new JLabel();
        ManagerNoTextField = new JTextField();
        EditApart = new JButton();
        CloseApartUpdate = new JButton();

        SetColorKt.setWhite(EditApart,CloseApartUpdate);

        jLabel2.setFont(new Font("微软雅黑", 1, 21)); // NOI18N
        jLabel2.setText("修改公寓楼信息");

        NoLabe.setText("公寓号：");

        NameLabe.setText("公寓名：");

        LocationLabe.setText("地    点：");

        FloorLabe.setText("层    数：");

        MaxLabe.setText("可容纳人数：");

        InLabe.setText("现住人数：");
        ManagerNoLabe.setText("负责人：");

        NoTextField.setText(agoApartment.getNo());
        NameTextField.setText(agoApartment.getName());
        LocationTextField.setText(agoApartment.getLocation());
        FloorTextField.setText(String.valueOf(agoApartment.getFloor()));
        MaxTextField.setText(String.valueOf(agoApartment.getMax()));
        InTextField.setText(String.valueOf(agoApartment.getIn()));
        ManagerNoTextField.setText(agoApartment.getManagerNo());

        EditApart.setText("确定");
        EditApart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditApartActionPerformed(evt);
            }
        });

        CloseApartUpdate.setText("返回");
        CloseApartUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseApartUpdateActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addComponent(LocationLabe)
                                                        .addComponent(FloorLabe)
                                                        .addComponent(NameLabe)
                                                        .addComponent(NoLabe))
                                                .addGap(41, 41, 41))
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addComponent(MaxLabe, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addComponent(ManagerNoLabe)
                                                                .addComponent(InLabe)))
                                                .addGap(26, 26, 26)))
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(InTextField, GroupLayout.Alignment.TRAILING)
                                        .addComponent(MaxTextField, GroupLayout.Alignment.TRAILING)
                                        .addComponent(FloorTextField, GroupLayout.Alignment.TRAILING)
                                        .addComponent(LocationTextField)
                                        .addComponent(ManagerNoTextField)
                                        .addComponent(NameTextField)
                                        .addComponent(NoTextField))
                                .addGap(44, 44, 44))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(165, 165, 165)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(jLabel2)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(92, Short.MAX_VALUE)
                                .addComponent(EditApart)
                                .addGap(73, 73, 73)
                                .addComponent(CloseApartUpdate)
                                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(NoLabe, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(NoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(NameLabe)
                                        .addComponent(NameTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(LocationLabe)
                                        .addComponent(LocationTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(FloorTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FloorLabe))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(MaxLabe)
                                        .addComponent(MaxTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(InLabe)
                                        .addComponent(InTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(ManagerNoLabe)
                                        .addComponent(ManagerNoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(EditApart)
                                        .addComponent(CloseApartUpdate))
                                .addGap(31, 31, 31))
        );
        Dimension screenDimension;
        screenDimension = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(400,520);
        setLocation((screenDimension.width -getWidth())/2 ,(screenDimension.height-getHeight())/2);
        pack();
    }// </editor-fold>

    private void EditApartActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        apartment = new Apartment(NoTextField.getText(),NameTextField.getText(),
                LocationTextField.getText(),Integer.valueOf(FloorTextField.getText()),
                Integer.valueOf(MaxTextField.getText()),Integer.valueOf(InTextField.getText()),
                ManagerNoTextField.getText());

        int result=new UpdateApartment().update(agoApartment,apartment);
        if(result >= 0) {
            JOptionPane.showMessageDialog(EditApartmentJFrame.this,
                    "修改成功！","提示",JOptionPane.INFORMATION_MESSAGE);
            EditApartmentJFrame.this.dispose();
        }
        else JOptionPane.showMessageDialog(EditApartmentJFrame.this,
                "修改失败！","警告",JOptionPane.WARNING_MESSAGE);
    }


    private void CloseApartUpdateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int flag = 0;
        flag = JOptionPane.showConfirmDialog(EditApartmentJFrame.this,
                "是否确定返回？","提示",JOptionPane.YES_NO_OPTION);
        if (flag == JOptionPane.YES_OPTION){
            EditApartmentJFrame.this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
     //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditApartmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditApartmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditApartmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditApartmentJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        Create and display the form

    }*/

    // Variables declaration - do not modify
    private JButton EditApart;
    private JButton CloseApartUpdate;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel NoLabe;
    private JLabel NameLabe;
    private JLabel LocationLabe;
    private JLabel FloorLabe;
    private JLabel MaxLabe;
    private JLabel InLabe;
    private JLabel ManagerNoLabe;
    private JTextField NoTextField;
    private JTextField NameTextField;
    private JTextField LocationTextField;
    private JTextField FloorTextField;
    private JTextField MaxTextField;
    private JTextField InTextField;
    private JTextField ManagerNoTextField;
    // End of variables declaration
}

