/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.supervisor;

import model.Apartment;
import model.Dorm;
import model.user.Admin;
import model.user.Student;
import funcation.*;
import funcation.delete.DeleteAdmin;
import funcation.delete.DeleteApartment;
import funcation.delete.DeleteDorm;
import funcation.delete.DeleteStudent;
import funcation.select.SelectAdminInfo;
import funcation.select.SelectApartments;
import funcation.select.SelectDorms;
import funcation.select.SelectStudentsInfo;
import util.JFrameUtilKt;
import util.SetColorKt;
import util.StackFrame;
import view.ChooseFrame;
import view.admin.AdminEditFrame;
import view.menu.SupervisorMenu;
import view.student.StudentEditFrame;

import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.Map;
import java.util.Vector;

/**
 *
 * @author Joki
 */
public class SupervisorBaseServiceFrame extends StackFrame implements ActionListener{

    /**
     * Creates new form NewJFrame
     */
    public SupervisorBaseServiceFrame() {
        super("Supervisor Basic Service");
        initComponents();
        JFrameUtilKt.init(this,750,570);

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrameUtilKt.quit(SupervisorBaseServiceFrame.this);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        apartTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        apartmentInfoArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        apartTextFiled = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        apartSelect = new javax.swing.JButton();
        apartInsert = new javax.swing.JButton();
        apartEdit = new javax.swing.JButton();
        apartDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        dormTable = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        dormTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dormSelect = new javax.swing.JButton();
        jScrollPane12 = new javax.swing.JScrollPane();
        dormTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        dormInsert = new javax.swing.JButton();
        dormEdit = new javax.swing.JButton();
        dormDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        dormApartTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JLabel();
        adminSelect = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        adminInfoArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        adminInsert = new javax.swing.JButton();
        adminEdit = new javax.swing.JButton();
        adminDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        adminTextFiled = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentSelect = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        studentTextArea = new javax.swing.JTextArea();
        studentTextField = new JTextField();
        jLabel4 = new javax.swing.JLabel();
        studentInsert = new javax.swing.JButton();
        studentEdit = new javax.swing.JButton();
        studentDelete = new javax.swing.JButton();
        bt_back1 = new javax.swing.JButton("返回");
        bt_back2 = new JButton("返回");
        bt_back3 = new JButton("返回");
        bt_back4 = new JButton("返回");

        bt_back1.addActionListener(this);
        bt_back2.addActionListener(this);
        bt_back3.addActionListener(this);
        bt_back4.addActionListener(this);

        SetColorKt.setWhite(bt_back1,bt_back2,bt_back3,bt_back4,
                apartSelect,apartInsert, apartEdit,apartDelete,
                dormSelect,dormInsert,dormEdit,dormDelete,
                studentSelect,studentInsert,studentEdit,studentDelete,
                adminSelect,adminInsert,adminEdit,adminDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 500));

        jTabbedPane1.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N

        /**
         * 公寓信息管理界面
         */
        apartTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "公寓号", "公寓名",  "负责人"
                }
        ));

        apartmentInfoArea.setEditable(false);

        apartTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                //鼠标点击时的处理
                apartmentInfoArea.setText(ApartTableKt.getApartInfo(apartTable).toString());//获取到所选行的公寓号
            }

            @Override
            public void mousePressed(MouseEvent e) {
                //鼠标按下时的处理
                apartmentInfoArea.setText("");
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                //鼠标松开时的处理
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                //鼠标进入表格时的处理
                //ApartTableKt.fillTable(apartTable,new SelectApartments().searchAll());//向公寓表填充信息
            }

            @Override
            public void mouseExited(MouseEvent e) {
                //鼠标退出表格时的处理
            }
        });
        ApartTableKt.fillTable(apartTable,new SelectApartments().searchAll());//向公寓表填充信息


        jScrollPane1.setViewportView(apartTable);

        apartmentInfoArea.setColumns(1);
        apartmentInfoArea.setRows(8);
        jScrollPane2.setViewportView(apartmentInfoArea);

        jLabel1.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel1.setText("详细信息");

        jScrollPane3.setViewportView(apartTextFiled);

        jLabel2.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel2.setText("公寓号");

        apartSelect.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        apartSelect.setText("查询");
        apartSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartSelectActionPerformed(evt);
            }
        });

        apartInsert.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        apartInsert.setText("添加");
        apartInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartInsertActionPerformed(evt);
            }
        });

        apartEdit.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        apartEdit.setLabel("修改");
        apartEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Apartment apartment1=null;
                try{
                    apartment1=ApartTableKt.getApartInfo(apartTable).get(0);
                    new EditApartmentJFrame(apartment1);}
                catch (Exception e1){
                    JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                            "请选择一条信息修改！","警告",JOptionPane.WARNING_MESSAGE);
                }
                ApartTableKt.fillTable(apartTable,new SelectApartments().searchAll());
            }
        });

        apartDelete.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        apartDelete.setText("删除");

        /**
         *公寓删除按钮的点击事件
         */
        apartDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                ArrayList<String> arrayList = GetSelectRowsValueKt.getSelectRowsValue(apartTable);

                for (String str : arrayList){
                    System.out.println(str);
                    int i = new DeleteApartment().Delete(str);
                    if (i == -1){
                        JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                                "你不能删除这个楼！","警告",JOptionPane.WARNING_MESSAGE);
                    }else {
                        JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                                "删除成功！","提醒",JOptionPane.INFORMATION_MESSAGE);
                        ApartTableKt.fillTable(apartTable,new SelectApartments().searchAll());
                    }
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(apartSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(jLabel1)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(apartInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(apartEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(apartDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51,51,51)
                                .addComponent(bt_back1, GroupLayout.PREFERRED_SIZE,100,GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(apartSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bt_back1,GroupLayout.PREFERRED_SIZE,35,GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apartInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apartEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(apartDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jTabbedPane1.addTab("公寓信息", jPanel1);

        /**
         * 宿舍管理信息界面
         */
        dormTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "公寓号", "宿舍号", "已住人数"
                }
        ));

        DormTableKt.fillTable(dormTable,new SelectDorms().searchAllDorms());

        dormTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                dormTextArea.setText(DormTableKt.getDormInfo(dormTable).toString());
            }

            @Override
            public void mousePressed(MouseEvent e) {
                dormTextArea.setText("");
            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });

        jScrollPane10.setViewportView(dormTable);

        jScrollPane11.setViewportView(dormTextField);

        jLabel7.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel7.setText("宿舍号");

        dormSelect.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        dormSelect.setText("查询");
        dormSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dormSelectActionPerformed(evt);
            }
        });

        dormTextArea.setColumns(20);
        dormTextArea.setRows(5);
        jScrollPane12.setViewportView(dormTextArea);

        jLabel8.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel8.setText("详细信息");

        dormInsert.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        dormInsert.setText("添加");
        dormInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dormInsertActionPerformed(evt);
            }
        });

        dormEdit.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        dormEdit.setLabel("修改");
        /**
         * 宿舍修改按钮的点击事件
         */
        dormEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Dorm dorm1=null;
                try{dorm1=DormTableKt.getDormInfo(dormTable);
                    new EditDormFrame(dorm1);}
                catch(Exception e1){

                    JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                            "请选择一条信息修改！","警告",JOptionPane.WARNING_MESSAGE);}

                DormTableKt.fillTable(dormTable,new SelectDorms().searchAllDorms());

            }
        });

        dormDelete.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        dormDelete.setText("删除");
        dormDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Map<String,String> dorm = GetSelectRowsValueKt.getSelectMap(dormTable);


                for (Map.Entry<String,String> entry : dorm.entrySet()){
                    int i = new DeleteDorm().delete(entry.getKey(),entry.getValue());
                    if (i == -1){
                        JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                                "删除失败！","警告",JOptionPane.WARNING_MESSAGE);
                    }else {
                        JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                                "删除成功！","提醒",JOptionPane.INFORMATION_MESSAGE);
                        DormTableKt.fillTable(dormTable,new SelectDorms().searchAllDorms());
                    }
                }
            }
        });

        jLabel9.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel9.setText("公寓号");

        jScrollPane13.setViewportView(dormApartTextField);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dormSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                                .addGap(86, 86, 86)
                                                                                .addComponent(jLabel8))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                                                .addGap(11, 11, 11)
                                                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(dormInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(dormEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(dormDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51,51,51)
                                .addComponent(bt_back2, GroupLayout.PREFERRED_SIZE,100,GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dormSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bt_back2,GroupLayout.PREFERRED_SIZE,35,GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dormInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dormEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dormDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jTabbedPane1.addTab("宿舍信息", jPanel2);

        /**
         *宿管信息子界面
         */
        adminTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "工号", "姓名", "管理公寓", "联系方式"
                }
        ));

        adminInfoArea.setEditable(false);//详细信息区域设为不可更改

        AdminTableKt.fillTable(adminTable,new SelectAdminInfo().selectAll());

        adminTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                adminInfoArea.setText(AdminTableKt.getAdminInfo(adminTable).toString());
            }

            @Override
            public void mousePressed(MouseEvent e) {
                adminInfoArea.setText("");
            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });

        jScrollPane7.setViewportView(adminTable);

        jScrollPane8.setViewportView(adminTextFiled);

        jLabel5.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel5.setText("   工号");

        adminSelect.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        adminSelect.setText("查询");
        adminSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSelectActionPerformed(evt);
            }
        });

        adminInfoArea.setColumns(20);
        adminInfoArea.setRows(5);
        jScrollPane9.setViewportView(adminInfoArea);

        jLabel6.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel6.setText("详细信息");

        adminInsert.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        adminInsert.setText("添加");
        adminInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminInsertActionPerformed(evt);
            }
        });

        adminEdit.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        adminEdit.setLabel("修改");
        adminEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new AdminEditFrame().fillText(AdminTableKt.getAdminInfo(adminTable));
            }
        });

        adminDelete.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        adminDelete.setText("删除");
        adminDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ArrayList<String> arrayList = GetSelectRowsValueKt.getSelectRowsValue(adminTable);

                for (String str : arrayList){
                    System.out.println(str);
                    int i = new DeleteAdmin().Delete(str);
                    if (i == -1){
                        JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                                "删除失败！","警告",JOptionPane.WARNING_MESSAGE);
                    }else {
                        JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                                "删除成功！","提醒",JOptionPane.INFORMATION_MESSAGE);
                        AdminTableKt.fillTable(adminTable,new SelectAdminInfo().selectAll());
                    }
                }
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane8, 100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(adminSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(jLabel6)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(adminInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(adminEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(adminDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51,51,51)
                                .addComponent(bt_back3, GroupLayout.PREFERRED_SIZE,100,GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(adminSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bt_back3,GroupLayout.PREFERRED_SIZE,35,GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jTabbedPane1.addTab("职工信息", jPanel3);

        /**
         * 学生信息子界面
         */
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "学号", "姓名", "联系方式"
                }
        ));

        StudentTableKt.fillTable(studentTable,new SelectStudentsInfo().selectAll());

        studentTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                studentTextArea.setText(StudentTableKt.getStudentInfo(studentTable).toString());
            }

            @Override
            public void mousePressed(MouseEvent e) {
                studentTextArea.setText("");
            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });

        jScrollPane4.setViewportView(studentTable);

        jScrollPane5.setViewportView(studentTextField);

        jLabel3.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel3.setText("   学号");

        studentSelect.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        studentSelect.setText("查询");
        studentSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSelectActionPerformed(evt);
            }
        });

        studentTextArea.setColumns(20);
        studentTextArea.setRows(5);
        jScrollPane6.setViewportView(studentTextArea);

        studentTextArea.setEditable(false);

        jLabel4.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        jLabel4.setText("详细信息");

        studentInsert.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        studentInsert.setText("添加");
        studentInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInsertActionPerformed(evt);
            }
        });

        studentEdit.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        studentEdit.setLabel("修改");
        studentEdit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new StudentEditFrame().fillText(StudentTableKt.getStudentInfo(studentTable));
            }
        });

        studentDelete.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        studentDelete.setText("删除");
        studentDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ArrayList<String> arrayList = GetSelectRowsValueKt.getSelectRowsValue(studentTable);

                for (String str : arrayList){
                    System.out.println(str);
                    int i = new DeleteStudent().Delete(str);
                    if (i == -1){
                        JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                                "删除失败！","警告",JOptionPane.WARNING_MESSAGE);
                    }else {
                        JOptionPane.showMessageDialog(SupervisorBaseServiceFrame.this,
                                "删除成功！","提醒",JOptionPane.INFORMATION_MESSAGE);
                        StudentTableKt.fillTable(studentTable,new SelectStudentsInfo().selectAll());
                    }
                }
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(studentSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addGap(86, 86, 86)
                                                .addComponent(jLabel4)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(studentInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(studentEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(studentDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51,51,51)
                                .addComponent(bt_back4, GroupLayout.PREFERRED_SIZE,100,GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane5, GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(studentSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bt_back4,GroupLayout.PREFERRED_SIZE,35,GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jTabbedPane1.addTab("学生信息", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>


    /**
     * 公寓号查询
     * @param evt
     */
    private void apartSelectActionPerformed(java.awt.event.ActionEvent evt) {

        String no = apartTextFiled.getText();//得到输入的公寓号


        if (no.isEmpty()){
            System.out.println("isEmp");
            ApartTableKt.fillTable(apartTable,new SelectApartments().searchAll());//向公寓表填充信息
        }else {
            System.out.println("notEmp");
            Vector<Apartment> apartments  = new SelectApartments().search(no);
            ApartTableKt.fillTable(apartTable,apartments);
        }


    }

    /**
     * 公寓添加按钮的点击事件
     * @param evt
     */
    private void apartInsertActionPerformed(java.awt.event.ActionEvent evt) {
        new InsertApartmentInfoFrame();
        ApartTableKt.fillTable(apartTable,new SelectApartments().searchAll());
    }

    private void studentSelectActionPerformed(java.awt.event.ActionEvent evt) {
        String no = studentTextField.getText();

        if (no.isEmpty()){
            StudentTableKt.fillTable(studentTable,new SelectStudentsInfo().selectAll());
        }else {
            Vector<Student> students = new Vector<>();
            students.add(new SelectStudentsInfo().select(no));
            StudentTableKt.fillTable(studentTable,students);
        }
    }

    private void studentInsertActionPerformed(java.awt.event.ActionEvent evt) {
        new InsertStudentFrame();
        StudentTableKt.fillTable(studentTable,new SelectStudentsInfo().selectAll());
    }

    /**
     * 宿管界面查询按钮的点击事件
     * @param evt
     */
    private void adminSelectActionPerformed(java.awt.event.ActionEvent evt) {

        String no = adminTextFiled.getText();//得到输入的工号

        if (no.isEmpty()){
            AdminTableKt.fillTable(adminTable,new SelectAdminInfo().selectAll());//向adminTable填充信息
        }else {
            Vector<Admin> admins = new Vector<>();
            admins.add(new SelectAdminInfo().select(no));
            AdminTableKt.fillTable(adminTable,admins);
        }
    }

    /**
     * 职工添加按钮点击事件
     * @param evt
     */
    private void adminInsertActionPerformed(java.awt.event.ActionEvent evt) {
        new InsertAdminInfoFrame();
        AdminTableKt.fillTable(adminTable,new SelectAdminInfo().selectAll());
}

    private void dormSelectActionPerformed(java.awt.event.ActionEvent evt) {
        String apartNo = dormApartTextField.getText();
        String dormNo = dormTextField.getText();

        if (apartNo.isEmpty() && dormNo.isEmpty()){
            DormTableKt.fillTable(dormTable,new SelectDorms().searchAllDorms());
        }else if (!apartNo.isEmpty() && dormNo.isEmpty()) {

            Vector<Dorm> dorms = (new SelectDorms().search(apartNo,"any(select dormNo from dorm)"));
            DormTableKt.fillTable(dormTable,dorms);
        }else if (!apartNo.isEmpty() && !dormNo.isEmpty()){

            Vector<Dorm> dorms = (new SelectDorms().search(apartNo,"'"+dormNo +"'"));
            DormTableKt.fillTable(dormTable,dorms);
        }
    }

    private void dormInsertActionPerformed(java.awt.event.ActionEvent evt) {
        new InsertDormFrame();
        DormTableKt.fillTable(dormTable,new SelectDorms().searchAllDorms());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupervisorBaseServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupervisorBaseServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupervisorBaseServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupervisorBaseServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupervisorBaseServiceFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JButton apartSelect;
    private javax.swing.JButton adminInsert;
    private javax.swing.JButton adminEdit;
    private javax.swing.JButton adminDelete;
    private javax.swing.JButton dormSelect;
    private javax.swing.JButton dormInsert;
    private javax.swing.JButton dormEdit;
    private javax.swing.JButton dormDelete;
    private javax.swing.JButton apartInsert;
    private javax.swing.JButton apartEdit;
    private javax.swing.JButton apartDelete;
    private javax.swing.JButton studentSelect;
    private javax.swing.JButton studentInsert;
    private javax.swing.JButton studentEdit;
    private javax.swing.JButton studentDelete;
    private javax.swing.JButton adminSelect;
    private javax.swing.JButton bt_back1;
    private JButton bt_back2;
    private JButton bt_back3;
    private JButton bt_back4;
    private javax.swing.JTextField apartTextFiled;
    private javax.swing.JTextField studentTextField;
    private javax.swing.JTextField adminTextFiled;
    private javax.swing.JTextField dormTextField;
    private javax.swing.JTextField dormApartTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable apartTable;
    private javax.swing.JTable studentTable;
    private javax.swing.JTable adminTable;
    private javax.swing.JTable dormTable;
    private javax.swing.JTextArea apartmentInfoArea;
    private javax.swing.JTextArea studentTextArea;
    private javax.swing.JTextArea adminInfoArea;
    private javax.swing.JTextArea dormTextArea;

    /**
     * back按钮的点击事件
     * @param e
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        if ((e.getSource() == bt_back1) || (e.getSource() == bt_back2)
                ||(e.getSource() ==  bt_back3) || (e.getSource() ==bt_back4)){
            new ChooseFrame();
            this.dispose();
        }
    }
    // End of variables declaration
}
